server:
  port: 8900

spring:
  application:
    name: leave-booking-system
  datasource:
    url: jdbc:h2:file:./data/leavebooking;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    ssl:
      enabled: false

firebase:
  web-api-key: AIzaSyCxZeTBdNzzZ2UvtnkvEuQcam95KzCY6Ck

rabbitmq:
  outbox:
    bindings:
      "[com.staffs.leavebooking.common.events.StaffMemberAddedEvent]":
        exchange: "staff-management"
        routing-key: "staff.member.added"
      "[com.staffs.leavebooking.common.events.StaffMemberUpdatedEvent]":
        exchange: "staff-management"
        routing-key: "staff.member.updated"
      "[com.staffs.leavebooking.common.events.ManagerNotificationEvent]":
        exchange: "leave-notifications"
        routing-key: "notification.manager.pending"
      "[com.staffs.leavebooking.common.events.StaffNotificationEvent]":
        exchange: "leave-notifications"
        routing-key: "notification.staff.decided"
